export const caseStudies = [
    {
      id: "afmaal",
      title: "Afmaal App",
      client: "Mazeed Technology",
      brief: "Afmaal APP is a vocabulary builder designed to enhance language learning in English. This project was both an exciting and challenging endeavor, reflecting my commitment to creating tools that facilitate learning and bridge language gaps.",
      image: "/images/afmaal.PNG",
      tags: ["Education", "PWA", "React"],
      challenges: "The main challenge was creating an intuitive interface that could effectively present vocabulary in a way that promotes retention and regular usage.",
      solution: "We implemented a spaced repetition system and gamification elements to make learning engaging and effective.",
      results: "The app has seen a 40% increase in user engagement and a 25% improvement in vocabulary retention rates among its users.",
    },
    {
      id: "opex-dashboard",
      title: "OPEX Dashboard",
      client: "Neogrant Oy",
      brief: "Accounting and financial management genuinely from one place. Increase work enjoyment and stay up to date with tasks All under one application",
      image: "/images/opex.PNG",
      tags: ["SaaS", "Dashboard", "React", "TypeScript"],
      challenges: "The main challenge was integrating multiple financial data sources and presenting them in a clear, actionable format.",
      solution: "We developed a modular dashboard system with customizable widgets and real-time data visualization.",
      results: "The dashboard has reduced the time spent on financial reporting by 60% and improved decision-making processes for our client.",
    },
    {
      id: "web-app",
      title: "MATCO Web Application",
      client: "Matco",
      brief: "Modern Automotive Technology (MATCO) is a modern workshop and car sales center based in Somaliland. They needed a web application to showcase their services and inventory.",
      image: "/images/matco.PNG",
      tags: ["Web App", "React", "Next.js", "TypeScript"],
      challenges: "The main challenge was creating a fast, responsive web application that could handle a large inventory of vehicles and services.",
      solution: "We utilized Next.js for server-side rendering and implemented a robust search and filter system for the inventory.",
      results: "The web application has increased online inquiries by 75% and improved the overall user experience, leading to a 30% increase in lead generation.",
    },
    {
      id: "recordr",
      title: "RecorDr",
      client: "Neogrant Oy",
      brief: "An AI-powered speech-to-text tool listens to doctor-patient conversations, generating real-time patient notes and catering to various healthcare roles, aiming to support a sustainable healthcare system.",
      image: "/images/recordr.PNG",
      tags: ["Web App", "React", "Next.js", "TypeScript", "AI"],
      challenges: "The main challenge was creating a fast, responsive web application that could handle a large inventory of vehicles and services.",
      solution: "We utilized Next.js for server-side rendering and implemented a robust search and filter system for the inventory.",
      results: "The web application has increased online inquiries by 75% and improved the overall user experience, leading to a 30% increase in lead generation.",
    },
    {
      id: "mazeedapp",
      title: "Mazeed Application",
      client: "Mazeed Technology",
      brief: "MAZEED App, the revolutionary digital ticket app that puts the power of event creation in the hands of the users, without the need for a large capital investment",
      image: "/images/mazeedapp.PNG",
      tags: ["Web App", "React", "Next.js", "TypeScript"],
      challenges: "The main challenge was creating a fast, responsive web application that could handle a large inventory of vehicles and services.",
      solution: "We utilized Next.js for server-side rendering and implemented a robust search and filter system for the inventory.",
      results: "The web application has increased online inquiries by 75% and improved the overall user experience, leading to a 30% increase in lead generation.",
    },
  ];