import React from "react";
import Head from "next/head";
import Footer from "../Footer";
import Navbar from "../Navbar";
import Container from "../Container/Container";

const Layout = ({ children }: { children: React.ReactNode }) => {
  return (
    <div className="bg-blue-50">
      <Head>
        <title>Ridwan Mohamed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
      <div>
        <Navbar />
      </div>
      <main>{children}</main>
      <div>
        <Footer />
      </div>
      </Container>
    </div>
  );
};

export default Layout;
