import React from "react";
import Head from "next/head";

import Footer from "../Footer";
import Navbar from "../Navbar";

const Layout = ({ children, className }: { children: React.ReactNode, className: string }) => {
  return (
    <div className={`bg-blue-50 ${className}`}>
      <Head>
        <title>Ridwan Mohamed - Site</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
      </div>
      <main>{children}</main>
      <div>
        <Footer />
      </div>
    </div>
  );
};

export default Layout;
