import Head from "next/head";
import { Inter } from "@next/font/google";

import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import Project from "../components/Projects";
import Container from "../components/Container/Container";
import projects from "../dummyData";
import Footer from "../components/Footer";
// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  
  return (
    <Container>
      <Head>
        <title>Ridwan Mohamed</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="mb-10"></div>
      <Hero />
      <div className="mb-10"></div>
     <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-10 w-full h-full">
     {projects.map((project) => (
        <Project key={project.id} project={project} />
      ))}
     </div>
     <Footer />
    </Container>

  );
}
